FROM nginx:latest

# Copier les fichiers front-end vers le bon dossier
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end

COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf
